services:
  - type: web
    name: safety-intelligence-backend
    env: python
    dockerfilePath: ./backend/Dockerfile
    region: ohio
    plan: starter
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ROBOFLOW_API_KEY
        sync: false
